#!/bin/sh

sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_EtOH_rep1.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_EtOH_rep2.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_EtOH_rep3.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881_rep1.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881_rep2.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881_rep3.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_E2_rep1.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_E2_rep2.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_E2_rep3.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881+E2_rep1.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881+E2_rep2.sh
sbatch scripts/rnaseq_EAW_pipeline/04_align_with_STAR_human/batch_sh/align_with_STAR_human_VCap_RNA_R1881+E2_rep3.sh