#!/bin/sh

sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep1_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep1_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep2_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep2_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep3_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_EtOH_rep3_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep1_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep1_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep2_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep2_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep3_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881_rep3_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep1_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep1_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep2_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep2_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep3_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_E2_rep3_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep1_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep1_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep2_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep2_R2.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep3_R1.sh
sbatch scripts/rnaseq_EAW_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_VCap_RNA_R1881+E2_rep3_R2.sh